// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/totoafya-screens/HomeDashboard.tsx": () => import("../components/mockups/totoafya-screens/HomeDashboard.tsx"),
  "./components/mockups/totoafya-screens/Onboarding.tsx": () => import("../components/mockups/totoafya-screens/Onboarding.tsx"),
  "./components/mockups/totoafya-screens/VaccineSchedule.tsx": () => import("../components/mockups/totoafya-screens/VaccineSchedule.tsx")
};
